# Generated by Django 4.0.6 on 2022-07-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_link',
            field=models.URLField(default=1, verbose_name='Ссылка на профиль'),
            preserve_default=False,
        ),
    ]
